Python Web Sep 2022/petstagram/petstagram/photos/urls.py
from django.urls import path, include

from petstagram.photos.views import add_photo, details_photo, edit_photo, delete_photo

urlpatterns = (
    path('add/', add_photo, name='add photo'),
    path('<int:pk>/', include([
        path('', details_photo, name='details photo'),
        path('edit/', edit_photo, name='edit photo'),
        path('delete/', delete_photo, name='delete photo'),
    ])),
)

Python Web Sep 2022/petstagram/petstagram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('petstagram.common.urls')),
    path('accounts/', include('petstagram.accounts.urls')),
    path('pets/', include('petstagram.pets.urls')),
    path('photos/', include('petstagram.photos.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Python Web Sep 2022/petstagram/deployment_demo/petstagram/petstagram/photos/models.py
# photos/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinLengthValidator
from django.db import models

from cloudinary import models as cloudinary_models

from petstagram.core.model_mixins import StrFromFieldsMixin
from petstagram.pets.models import Pet
from petstagram.photos.validators import validate_file_less_than_5mb

UserModel = get_user_model()


class Photo(StrFromFieldsMixin, models.Model):
    str_fields = ('pk', 'photo', 'location')
    MIN_DESCRIPTION_LENGTH = 10
    MAX_DESCRIPTION_LENGTH = 300

    MAX_LOCATION_LENGTH = 30

    # Requires mediafiles to work correctly
    photo = cloudinary_models.CloudinaryField(
        null=False,
        blank=True,
        # validators=(validate_file_less_than_5mb,),
    )

    description = models.CharField(
        # DB validation
        max_length=MAX_DESCRIPTION_LENGTH,
        validators=(
            # Django/python validation, not DB validation
            MinLengthValidator(MIN_DESCRIPTION_LENGTH),
        ),
        null=True,
        blank=True,
    )

    location = models.CharField(
        max_length=MAX_LOCATION_LENGTH,
        null=True,
        blank=True,
    )

    publication_date = models.DateField(
        # Automatically sets current date on `save` (update or create)
        auto_now=True,
        null=False,
        blank=True,
    )

    # One-to-one relations

    # One-to-many relations

    user = models.ForeignKey(
        UserModel,
        on_delete=models.RESTRICT,
    )

    # Many-to-many relations

    tagged_pets = models.ManyToManyField(
        Pet,
        blank=True,
    )

Python Web Sep 2022/petstagram/petstagram/photos/models.py
# photos/models.py
from django.contrib.auth import get_user_model
from django.core import validators
from django.db import models

from petstagram.core.model_mixins import StrFromFieldsMixin
from petstagram.pets.models import Pet
from petstagram.photos.validators import validate_file_less_than_5mb


# Create your models here.


UserModel = get_user_model()


class Photo(StrFromFieldsMixin, models.Model):
    str_fields = ('pk', 'photo', 'location')

    MIN_DESCRIPTION_LENGTH = 10
    MAX_DESCRIPTION_LENGTH = 300

    MAX_LOCATION_LENGTH = 30

    # Requires media files to work correctly
    photo = models.ImageField(
        upload_to='pet_photos/',
        null=False,
        blank=True,
        validators=(
            validate_file_less_than_5mb,
        ),
    )

    description = models.CharField(
        # DB validation
        max_length=MAX_DESCRIPTION_LENGTH,
        validators=(
            # Django/python validation, not DB validation
            validators.MinLengthValidator(MIN_DESCRIPTION_LENGTH),
        ),
        null=True,
        blank=True,
    )

    location = models.CharField(
        max_length=MAX_LOCATION_LENGTH,
        null=True,
        blank=True,
    )

    publication_date = models.DateField(
        # Automatically sets current date on 'save' (create or update)
        auto_now=True,
        null=False,
        blank=True,
    )

    # One-to-one relations
    #
    # One-to-many relations

    user = models.ForeignKey(
        UserModel,
        on_delete=models.RESTRICT,
    )

    # Many-to-many relations

    tagged_pets = models.ManyToManyField(
        Pet,
        blank=True,
    )

Python Web Sep 2022/petstagram/petstagram/photos/forms.py
from django import forms
from django.core.exceptions import ValidationError

from petstagram.common.models import PhotoLike, PhotoComment
from petstagram.core.forms_mixins import DisabledFormMixin
from petstagram.photos.models import Photo


class PhotoBaseForm(forms.ModelForm):
    class Meta:
        model = Photo
        exclude = ('publication_date', 'user')


class PhotoCreateForm(PhotoBaseForm):
    pass


class PhotoEditForm(PhotoBaseForm):
    class Meta:
        model = Photo
        exclude = ('publication_date', 'photo')


class PhotoDeleteForm(DisabledFormMixin, PhotoBaseForm):
    disabled_fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    # Deleting the tagged pets
    def save(self, commit=True):
        if commit:
            self.instance.tagged_pets.clear()  # deleting many-to-many

            PhotoLike.objects.filter(photo_id=self.instance.id)\
                .delete()  # deleting one-to-many

            PhotoComment.objects.filter(photo_id=self.instance.id)\
                .delete()  # deleting one-to-many

            self.instance.delete()

        return self.instance

    # Raising Validation Error
    # def clean_tagged_pets(self):
    #     tagged_pets = self.cleaned_data['tagged_pets']
    #     if tagged_pets:
    #         raise ValidationError('Pets are tagged in this photo!')

Python Web Sep 2022/petstagram/petstagram/photos/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse

from petstagram.photos.forms import PhotoCreateForm, PhotoEditForm, PhotoDeleteForm
from petstagram.photos.models import Photo


# Create your views here.


def details_photo(request, pk):
    photo = Photo.objects \
        .filter(pk=pk) \
        .get()

    user_like_photos = Photo.objects.filter(pk=pk, user_id=request.user.pk)

    context = {
        'photo': photo,
        'has_user_liked_photo': user_like_photos,
        'likes_count': photo.photolike_set.count(),
        'is_owner': request.user == photo.user,
    }

    return render(
        request,
        'photos/photo-details-page.html',
        context,
    )


def get_post_photo_form(request, form, success_url, template_path, pk=None):
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect(success_url)

    context = {
        'form': form,
        'pk': pk,
    }

    return render(request, template_path, context)


@login_required
def add_photo(request):
    if request.method == "GET":
        form = PhotoCreateForm()
    else:
        form = PhotoCreateForm(request.POST, request.FILES)
        if form.is_valid():
            photo = form.save(commit=False)  # form.save() returns object saved

            photo.user = request.user
            photo.save()
            form.save_m2m()

            return redirect('details photo', pk=photo.pk)

    context = {
        'form': form
    }

    return render(
        request,
        'photos/photo-add-page.html',
        context,
    )


def edit_photo(request, pk):
    photo = Photo.objects\
        .filter(pk=pk)\
        .get()

    return get_post_photo_form(
        request,
        PhotoEditForm(request.POST or None, instance=photo),
        success_url=reverse('index'),
        template_path='photos/photo-edit-page.html',
        pk=pk,
    )


def delete_photo(request, pk):
    photo = Photo.objects \
        .filter(pk=pk) \
        .get()

    return get_post_photo_form(
        request,
        PhotoDeleteForm(request.POST or None, instance=photo),
        success_url=reverse('index'),
        template_path='photos/photo-delete-page.html',
        pk=pk,
    )

Python Web Sep 2022/petstagram/templates/photos/photo-add-page.html
{% extends 'base/base.html' %}
{% block page_content%}

    <!-- Start Add Photo Section -->
    <div class="edit-delete edit-photo">
        <h2>Add photo</h2>
        <!-- Start Add Photo Form -->
        <form method="post" action="{% url 'add photo' %}" enctype="multipart/form-data">
{#            <p>#}
{#                <label for="id_photo_file">Photo file:</label>#}
{#                <input type="file">#}
{#            </p>#}
{##}
{#            <p>#}
{#                <label for="id_description">Description:</label>#}
{#                <input type="text">#}
{#            </p>#}
{##}
{#            <p>#}
{#                <label for="id_description">Location:</label>#}
{#                <input type="text" name="photo_shooting_location" maxlength="50" id="id_photo_shooting_location">#}
{#            </p>#}
{##}
{#            <p>#}
{#                <label for="pets">Tag Pets:</label>#}
{##}
{#                <select name="pets" id="id_tagged_pets" multiple>#}
{#                    <option>Sasho</option>#}
{#                    <option>Perry</option>#}
{#                    <option>Bucky</option>#}
{#                    <option>Steve</option>#}
{#                </select>#}
{#            </p>#}
            {{ form.as_p }}
            <!-- Add Photo Button -->
            <button class="add-btn" type="submit">Add Photo</button>
            {% csrf_token %}
        </form>
        <!-- End Add Photo Form -->
    </div>
    <!-- End Add Photo Section -->

{% endblock %}

Python Web Sep 2022/petstagram/templates/photos/photo-delete-page.html
{% extends 'base/base.html' %}
{% block page_content%}
    <div class="edit-delete delete-photo">
        <h2>Delete photo</h2>
        <form method="post" action="{% url 'delete photo' pk=pk %}" enctype="multipart/form-data">
            {{ form.as_p }}
            <button class="delete-btn" type="submit">Delete Photo</button>
            {% csrf_token %}
        </form>
    </div>
{% endblock %}

Python Web Sep 2022/petstagram/templates/photos/photo-details-page.html
{% extends 'base/base.html' %}
{% load static %}

{% block page_content %}

    <div class="container">
        <div class="col-9">

            <!-- Start Pet Photo Post Section -->
            <div class="card">
                <div class="top">

                    <!-- Start User Details and Image Location Section -->
                    <div class="userDetails">

                        <!-- Link to User Profile Details Page-->
                        <a href="#">
                            <div class="profilepic">
                                <div class="profile_img">
                                    <div class="image">
                                        <img src="{% static 'images/person.png' %}" alt="img8">
                                    </div>
                                </div>
                            </div>
                        </a>
                        <h3>

                            <!-- Link to User Profile Details Page -->
                            <a href="#">
                                <!-- IF owner has first name and last name -->
                                {% if photo.user.get_full_name %}
                                    {{ photo.user.get_full_name }}
                                    <!-- else -->
                                    <!-- show user username -->
                                {% else %}
                                    {{ photo.user.username }}
                                {% endif %}
                            </a>
                            <br>

                            <!-- IF the photo has location -->
                            {% if photo.location %}
                                <span>{{ photo.location }}</span>
                            {% endif %}
                            <!-- IF the viewer is the creator of the photo -->
                            {% if is_owner %}
                                <div class="edit-delete-btns">

                                    <!-- Link to Edit Pet Photo Page -->
                                    <a href="{% url 'edit photo' pk=photo.pk %}">
                                        <img class="edit-img" src="{% static 'images/edit-pen-icon-6.jpg' %}"
                                             alt="edit button">
                                    </a>

                                    <!-- Link to Delete Pet Photo Page -->
                                    <a href="{% url 'delete photo' pk=photo.pk %}">
                                        <img class="bin-img" src="{% static 'images/icon-remove-22.jpg' %}"
                                             alt="bin button">
                                    </a>
                                </div>
                            {% endif %}
                            <!-- End IF the viewer is the creator of the photo -->

                        </h3>
                    </div>
                    <!-- End User Details and Image Location Section -->

                </div>

                <!-- Start Pet Photo -->
                <div class="imgBx" id="{{ photo.pk }}">
                    <!-- Pet Photo -->
                    <img src="/media/{{ photo.photo }}" alt="photo of the pets {{ photo.tagged_pets.all|join:',' }}"
                         class="cover">
                </div>
                <!-- End Pet Photo -->

                <div class="bottom">

                    <!-- Start Like and Share Buttons Section -->
                    <div class="actionBtns">
                        <div class="left">

                            <!-- Start Like Button -->
                            <span class="heart">

                                    <!-- Link to Like Path -->
									<a href="{% url 'like photo' photo_id=photo.pk %}">


                                        {% if has_user_liked_photo %}
                                            <!-- IF user has liked the photo -->
                                            <svg style="color: red"
                                                 xmlns="http://www.w3.org/2000/svg"
                                                 width="24"
                                                 height="24"
                                                 fill="currentColor"
                                                 class="bi bi-heart-fill"
                                                 viewBox="0 0 16 16">
                                            <!-- Coordinate path -->
                                            <path fill-rule="evenodd"
                                                  d="M8 1.314C12.438-3.248 23.534 4.735
                                                  8 15-7.534 4.736 3.562-3.248 8 1.314z"
                                                  fill="red">
                                            </path>
                                        </svg>
                                        {% else %}
                                            <!-- IF NOT user has liked the photo -->
                                            <svg aria-label="Like"
                                                 color="#262626"
                                                 fill="#262626"
                                                 height="24"
                                                 role="img"
                                                 viewBox="0 0 48 48"
                                                 width="24">
                                        <!-- Coordinate path -->
                                        <path d="M34.6 6.1c5.7 0 10.4 5.2 10.4
                                                    11.5 0 6.8-5.9 11-11.5 16S25 41.3 24
                                                    41.9c-1.1-.7-4.7-4-9.5-8.3-5.7-5-11.5-9.2-11.5-16C3
                                                    11.3 7.7 6.1 13.4 6.1c4.2 0 6.5 2 8.1 4.3
                                                    1.9 2.6 2.2 3.9 2.5 3.9.3 0 .6-1.3 2.5-3.9
                                                    1.6-2.3 3.9-4.3 8.1-4.3m0-3c-4.5 0-7.9
                                                    1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1
                                                    0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3
                                                    1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3
                                                    1.1.5 1.6.5.6 0 1.1-.2 1.6-.5 1-.6 2.8-2.2
                                                    7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6
                                                    48 25 48 17.6c0-8-6-14.5-13.4-14.5z">
                                        </path>
                                        </svg>
                                        {% endif %}



								    </a>
                            </span>
                            <!-- End Like Button -->

                            <!-- Start Share  Button -->

                            <!-- Link to Share Path -->
                            <a href="#">
                                <svg aria-label="Share Post" class="_8-yf5 " color="#262626" fill="#262626"
                                     height="24" role="img" viewBox="0 0 48 48" width="24">
                                    <path d="M47.8 3.8c-.3-.5-.8-.8-1.3-.8h-45C.9 3.1.3
										3.5.1 4S0 5.2.4 5.7l15.9 15.6 5.5 22.6c.1.6.6
										1 1.2 1.1h.2c.5 0 1-.3
										1.3-.7l23.2-39c.4-.4.4-1 .1-1.5zM5.2
										6.1h35.5L18 18.7 5.2 6.1zm18.7
										33.6l-4.4-18.4L42.4 8.6 23.9 39.7z">
                                    </path>
                                </svg>
                            </a>
                        </div>
                    </div>
                    <!-- End Like and Share Buttons Section -->

                    <!-- Number of Likes for the Photo -->
                    <p class="likes">{{ likes_count }} likes</p>

                    <!-- Start Tagged Pets Section-->
                    <!-- Link to First Tagged Pet Details Page -->
                    {% for pet in photo.tagged_pets.all %}
                        <a href="{% url 'details pet' pet_slug=pet.slug username=pet.user.username %}">
                            <p class="message">
                                <b>{{ pet.name }}</b>
                            </p>
                        </a>
                    {% endfor %}
                    <!-- Link to Second Tagged Pet Details Page -->
                    <a href="#">
                        <p class="message">
                            <b>Some other fish</b>
                        </p>
                    </a>
                    <!-- End Tagged Pets Section-->

                    <!-- Date of Publication or edit of the Photo -->
                    <h5 class="postTime">{{ photo.publication_date }}</h5>

                    <!-- Start Comments Section -->
                    <div class="comments">
                        <div class="top">
                            <div class="userDetails">
                                <div class="comment-data">
                                    <div class="profilepic">
                                        <div class="profile_img">
                                            <div class="image">
                                                <!-- User Profile Image -->
                                                <img src="{% static 'images/person.png' %}" alt="img8">
                                            </div>
                                        </div>
                                    </div>
                                    <p>
                                        <!-- Link to User Profile Details Page-->
                                        <!-- User First and/or Last Name or username-->
                                        <a href="">Steven Ivanov</a>
                                        <!-- User Comment -->
                                        - OMG where can i get one
                                    </p>
                                </div>
                                <span>Sept. 20, 2022, 5:02 p.m.</span>
                            </div>
                        </div>
                    </div>
                    <!-- End Comments Section -->
                </div>

                <!-- Start Add Comments Section -->
                <div class="addComments">
                    <div class="reaction">
                        <h3>
                            <i class="far fa-smile"></i>
                        </h3>
                    </div>

                    <!-- Start Add Comments Form -->
                    <form method="post" action="#">
                        <label for="id_body">Body:</label>
                        <textarea name="body" cols="40" rows="10" placeholder="Add comment..." maxlength="300"
                                  required="" id="id_body"></textarea>
                        <!-- Post Comments Button -->
                        <button type="submit">Post</button>
                    </form>
                    <!-- End Add Comments Form -->

                </div>
                <!-- End Add Comments Section -->

            </div>
            <!-- End Pet Photo Post Section -->

        </div>
    </div>

{% endblock %}

Python Web Sep 2022/petstagram/templates/photos/photo-edit-page.html
{% extends 'base/base.html' %}
{% block page_content%}

    <!-- Starts Edit Photo Section -->
    <div class="edit-delete edit-photo">
        <h2>Edit photo</h2>

        <!-- Starts Edit Photo Form -->
        <form method="post" action="{% url 'edit photo' pk=pk %}" enctype="multipart/form-data">
{#            <p>#}
{#                <label for="id_photo_file">Photo file:</label>#}
{#                <input type="file">#}
{#            </p>#}
{##}
{#            <p>#}
{#                <label for="id_description">Description:</label>#}
{#                <input type="text" value="Sasho is an Axolotl">#}
{#            </p>#}
{##}
{#            <p>#}
{#                <label for="id_description">Location:</label>#}
{#                <input type="text" name="photo_shooting_location" maxlength="50" id="id_photo_shooting_location"#}
{#                       value="Bansko, Bulgaria">#}
{#            </p>#}
{##}
{#            <p>#}
{#                <label for="pets">Tag Pets:</label>#}
{##}
{#                <select name="pets" id="id_tagged_pets" multiple>#}
{#                    <option selected>Sasho</option>#}
{#                    <option>Perry</option>#}
{#                    <option>Bucky</option>#}
{#                    <option>Steve</option>#}
{#                </select>#}
{#            </p>#}
            {{ form.as_p }}
            <!-- Edit Photo Button -->
            <button class="edit-btn" type="submit">Edit Photo</button>
            {% csrf_token %}
        </form>
        <!-- End Edit Photo Form -->

    </div>
    <!-- End Edit Photo Section -->

{% endblock %}