Python Web Sep 2022/exam_nov_2020/exam_nov_2020/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('exam_nov_2020.web.urls')),
]

Python Web Sep 2022/exam_nov_2020/exam_nov_2020/web/urls.py
from django.urls import path

from exam_nov_2020.web.views import home_page, create_recipe, edit_recipe, \
    delete_recipe, details_recipe

urlpatterns = (
    path('', home_page, name='home page'),
    path('create/', create_recipe, name='create recipe'),
    path('edit/<int:recipe_id>/', edit_recipe, name='edit recipe'),
    path('delete/<int:recipe_id>/', delete_recipe, name='delete recipe'),
    path('details/<int:recipe_id>/', details_recipe, name='details recipe'),
)

Python Web Sep 2022/exam_nov_2020/exam_nov_2020/web/models.py
from django.db import models

# Create your models here.


class Recipe(models.Model):
    title = models.CharField(
        verbose_name='Title',
        max_length=30,
    )

    image_url = models.URLField(
        verbose_name='Image URL',
    )

    description = models.TextField(
        verbose_name='Description',
    )

    ingredients = models.CharField(
        verbose_name='Ingredients',
        max_length=250,
    )

    time = models.IntegerField(
        verbose_name='Time',
    )

    class Meta:
        ordering = ('pk',)

Python Web Sep 2022/exam_nov_2020/exam_nov_2020/web/forms.py
from django import forms

from exam_nov_2020.web.models import Recipe


class CreateRecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = '__all__'
        widgets = {
            'title': forms.TextInput(
                attrs={
                    'placeholder': 'Title',
                }
            ),

            'image_url': forms.URLInput(
                attrs={
                    'placeholder': 'Image URL',
                }
            ),

            'description': forms.Textarea(
                attrs={
                    'placeholder': 'Description',
                }
            ),

            'ingredients': forms.TextInput(
                attrs={
                    'placeholder': 'Ingredient1, Ingredient2, Ingredient3...',
                }
            ),

            'time': forms.NumberInput(
                attrs={
                    'placeholder': 'cooking time in min'
                }
            ),
        }


class EditRecipeForm(CreateRecipeForm):
    pass


class DeleteRecipeForm(CreateRecipeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for (_, field) in self.fields.items():
            field.widget.attrs['disabled'] = 'disabled'
            field.widget.attrs['readonly'] = 'readonly'

Python Web Sep 2022/exam_nov_2020/exam_nov_2020/web/views.py
from django.shortcuts import render, redirect

from exam_nov_2020.web.forms import CreateRecipeForm, EditRecipeForm, DeleteRecipeForm
from exam_nov_2020.web.models import Recipe


# Create your views here.


def home_page(request):
    recipes = Recipe.objects.all()

    context = {
        'recipes': recipes,
    }

    return render(request, 'index.html', context)


def create_recipe(request):
    if request.method == 'GET':
        form = CreateRecipeForm()
    else:
        form = CreateRecipeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home page')

    context = {
        'form': form,
    }

    return render(request, 'create.html', context)


def edit_recipe(request, recipe_id):
    recipe = Recipe.objects.filter(pk=recipe_id).get()

    if request.method == 'GET':
        form = EditRecipeForm(instance=recipe)
    else:
        form = EditRecipeForm(request.POST, instance=recipe)
        if form.is_valid():
            form.save()
            return redirect('home page')

    context = {
        'form': form,
        'recipe_id': recipe_id,
    }

    return render(request, 'edit.html', context)


def delete_recipe(request, recipe_id):
    recipe = Recipe.objects.filter(pk=recipe_id).get()

    if request.method == 'GET':
        form = DeleteRecipeForm(instance=recipe)

    else:
        form = DeleteRecipeForm(request.POST, instance=recipe)
        recipe.delete()
        return redirect('home page')

    context = {
        'form': form,
        'recipe_id': recipe_id,
    }

    return render(request, 'delete.html', context)


def details_recipe(request, recipe_id):
    recipe = Recipe.objects.filter(pk=recipe_id).get()
    ingredients = recipe.ingredients.split(', ')

    context = {
        'recipe': recipe,
        'recipe_id': recipe_id,
        'ingredients': ingredients,
    }

    return render(request, 'details.html', context)

Python Web Sep 2022/exam_nov_2020/templates/create.html
{% load static %}

<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static '/css/style_recipes.css' %}">
    <title>Recipes</title>
</head>

<body>
     
 <nav>
    <ul>
        <img src="{% static 'images/chef.png' %}" alt="chef">
        <li class="title"><a href="{% url 'home page' %}">Recipes</a></li>
        <li><a href="{% url 'create recipe' %}">Add Recipe</a></li>
    </ul>
</nav>
    <div class="container">
        
<h1>Create Recipe</h1>
<div class="items-container">
    <div class="item">
{#        <form method="POST">#}
{#            <label for="title">Title</label>#}
{#            <input type="text" name="title" maxlength="30" required="" id="id_title">#}
{#            <label for="imageURL">Image URL</label>#}
{#            <input type="url" name="image_url" maxlength="200" required="" id="id_image_url">#}
{#            <label for="description">Description</label>#}
{#            <textarea name="description" cols="40" rows="10" required="" id="id_description"></textarea>#}
{#            <label for="ingredients">Ingredients</label>#}
{#            <input type="text" name="ingredients" maxlength="250" required="" id="id_ingredients">#}
{#            <label for="time">Time (Minutes)</label>#}
{#            <input type="number" name="time" required="" id="id_time">#}
{#            <input type="submit" value="Create">#}
{#        </form>#}

        <form method="post" action="{% url 'create recipe' %}">
            {{ form }}
            <input type="submit" value="Create">
            {% csrf_token %}
        </form>

    </div>
</div>

    </div>


</body></html>

Python Web Sep 2022/exam_nov_2020/templates/delete.html
{% load static %}

<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style_recipes.css' %}">
    <title>Recipes</title>
</head>

<body>
     
 <nav>
    <ul>
        <img src="{% static 'images/chef.png' %}" alt="chef">
        <li class="title"><a href="{% url 'home page' %}">Recipes</a></li>
        <li><a href="{% url 'create recipe' %}">Add Recipe</a></li>
    </ul>
</nav>
    <div class="container">
        
<h1>Delete Recipe</h1>
<div class="items-container">
    <div class="item">
{#        <form method="POST">#}
{#            <label for="title">Title</label>#}
{#            <input type="text" name="title" value="Homemade Chicken Soup" maxlength="30" disabled="" required="" id="id_title">#}
{#            <label for="imageURL">Image URL</label>#}
{#            <input type="url" name="image_url" value="https://i.ytimg.com/vi/o91gT73mQhg/maxresdefault.jpg" maxlength="200" disabled="" required="" id="id_image_url">#}
{#            <label for="description">Description</label>#}
{#            <textarea name="description" cols="40" rows="10" disabled="" required="" id="id_description">Put the chicken, carrots, celery and onion in a large soup pot and cover with cold water. Heat and simmer, uncovered, until the chicken meat falls off of the bones (skim off foam every so often).#}
{#Take everything out of the pot. Strain the broth. Pick the meat off of the bones and chop the carrots, celery and onion. Season the broth with salt, pepper and chicken bouillon to taste, if desired. Return the chicken, carrots, celery and onion to the pot, stir together, and serve.</textarea>#}
{#            <label for="ingredients">Ingredients</label>#}
{#            <input type="text" name="ingredients" value="1 (3 pound) whole chicken, 4 medium (blank)s carrots halved, 4 stalks celery halved, 1 large onion halved, water to cover, salt and pepper to taste, 1 teaspoon chicken bouillon granules" maxlength="250" disabled="" required="" id="id_ingredients">#}
{#            <label for="time">Time (Minutes)</label>#}
{#            <input type="number" name="time" value="30" disabled="" required="" id="id_time">#}
{#            <input type="submit" class="button delete" value="Delete">#}
{#        </form>#}

        <form method="post" action="{% url 'delete recipe' recipe_id=recipe_id %}">
            {{ form }}
            <input type="submit" class="button delete" value="Delete">
            {% csrf_token %}
        </form>

    </div>
</div>

    </div>


</body></html>

Python Web Sep 2022/exam_nov_2020/templates/details.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static '/css/style_recipes.css' %}">
    <title>Recipes</title>
</head>

<body>

<nav>
    <ul>
        <img src="{% static '/images/chef.png' %}" alt="chef">
        <li class="title"><a href="{% url 'home page' %}">Recipes</a></li>
        <li><a href="{% url 'create recipe' %}">Add Recipe</a></li>
    </ul>
</nav>
<div class="container">

    <h1>Recipe Details</h1>
    <div class="items-container">
        <div class="item">
            <h2>{{ recipe.title }}</h2>
            <img class="detail-img" src="{{ recipe.image_url }}" alt="{{ recipe.title }}">
            <div class="time">
                <img src="{% static '/images/clock.png' %}">
                <p>{{ recipe.time }}min</p>
            </div>
            <h3>Ingredients</h3>
            <ul>

                {#                        <li>1 (3 pound) whole chicken</li>#}
                {#                    #}
                {#                        <li>4 medium (blank)s carrots halved</li>#}
                {#                    #}
                {#                        <li>4 stalks celery halved</li>#}
                {#                    #}
                {#                        <li>1 large onion halved</li>#}
                {#                    #}
                {#                        <li>water to cover</li>#}
                {#                    #}
                {#                        <li>salt and pepper to taste</li>#}
                {#                    #}
                {#                        <li>1 teaspoon chicken bouillon granules</li>#}

                {% for ingredient in ingredients %}
                    <li>{{ ingredient }}</li>
                {% endfor %}

            </ul>
            <h3>How to prepare?</h3>
            <div class="recipe-info-full">
                {{ recipe.description }}
            </div>
            <div class="buttons-container">
                <a class="button edit" href="{% url 'edit recipe' recipe_id=recipe_id %}">Edit</a>
                <a class="button delete" href="{% url 'delete recipe' recipe_id=recipe_id %}">Delete</a>
            </div>
        </div>
    </div>

</div>


</body>
</html>

Python Web Sep 2022/exam_nov_2020/templates/edit.html
{% load static %}

<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static '/css/style_recipes.css' %}">
    <title>Recipes</title>
</head>

<body>
     
 <nav>
    <ul>
        <img src="{% static 'images/chef.png' %}" alt="chef">
        <li class="title"><a href="{% url 'home page' %}">Recipes</a></li>
        <li><a href="{% url 'create recipe' %}">Add Recipe</a></li>
    </ul>
</nav>
    <div class="container">
        
<h1>Edit Recipe</h1>
<div class="items-container">
    <div class="item">
{#        <form method="POST">#}
{#            <label for="title">Title</label>#}
{#            <input type="text" name="title" value="Homemade Chicken Soup" maxlength="30" required="" id="id_title">#}
{#            <label for="imageURL">Image URL</label>#}
{#            <input type="url" name="image_url" value="https://i.ytimg.com/vi/o91gT73mQhg/maxresdefault.jpg" maxlength="200"  required="" id="id_image_url">#}
{#            <label for="description">Description</label>#}
{#            <textarea name="description" cols="40" rows="10"  required="" id="id_description">Put the chicken, carrots, celery and onion in a large soup pot and cover with cold water. Heat and simmer, uncovered, until the chicken meat falls off of the bones (skim off foam every so often).#}
{#Take everything out of the pot. Strain the broth. Pick the meat off of the bones and chop the carrots, celery and onion. Season the broth with salt, pepper and chicken bouillon to taste, if desired. Return the chicken, carrots, celery and onion to the pot, stir together, and serve.</textarea>#}
{#            <label for="ingredients">Ingredients</label>#}
{#            <input type="text" name="ingredients" value="1 (3 pound) whole chicken, 4 medium (blank)s carrots halved, 4 stalks celery halved, 1 large onion halved, water to cover, salt and pepper to taste, 1 teaspoon chicken bouillon granules" maxlength="250"  required="" id="id_ingredients">#}
{#            <label for="time">Time (Minutes)</label>#}
{#            <input type="number" name="time" value="30" required="" id="id_time">#}
{#            <input type="submit" class="button edit" value="Edit">#}
{#        </form>#}

        <form method="post" action="{% url 'edit recipe' recipe_id=recipe_id %}">
            {{ form }}
            <input type="submit" class="button edit" value="Edit">
            {% csrf_token %}
        </form>

    </div>
</div>

    </div>


</body></html>

Python Web Sep 2022/exam_nov_2020/templates/index.html
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static '/css/style_recipes.css' %}">
    <title>Recipes</title>
</head>

<body>

<nav>
    <ul>
        <img src="{% static 'images/chef.png' %}" alt="chef">
        <li class="title"><a href="{% url 'home page' %}">Recipes</a></li>
        <li><a href="{% url 'create recipe' %}">Add Recipe</a></li>
    </ul>
</nav>
<div class="container">

    <h1>My Recipes</h1>
    {% if not recipes %}
        <h2>There are no recipes.</h2>
    {% else %}

        <div class="items-container">
            {#        <div class="item">#}
            {#            <h2>Homemade Chicken Soup</h2>#}
            {#            <img class="detail-img" src="https://i.ytimg.com/vi/o91gT73mQhg/maxresdefault.jpg" alt="recipe-image">#}
            {#            <div class="recipe-info">#}
            {#                Put the chicken, carrots, celery and onion in a large soup pot and cover with cold water. Heat and#}
            {#                simmer, uncovered, until the chicken meat falls off of the bones (skim off foam every so often). Take#}
            {#                everything out of the pot. Strain the broth. Pick#}
            {#                the meat off of the bones and chop the carrots, celery and onion. Season the broth with salt, pepper and#}
            {#                chicken bouillon to taste, if desired. Return the chicken, carrots, celery and onion to the pot, stir#}
            {#                together, and serve.#}
            {#            </div>#}
            {##}
            {#            <div class="buttons-container">#}
            {#                <a class="button detail" href="./details.html">Details</a>#}
            {#                <a class="button edit" href="./edit.html">Edit</a>#}
            {#                <a class="button delete" href="./delete.html">Delete</a>#}
            {#            </div>#}
            {#        </div>#}
            {##}
            {#        <div class="item">#}
            {#            <h2>Cardamom Maple Salmon (Edit)</h2>#}
            {#            <img class="detail-img"#}
            {#                 src="https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimages.media-allrecipes.com%2Fuserphotos%2F1122494.jpg&amp;w=596&amp;h=596&amp;c=sc&amp;poi=face&amp;q=85"#}
            {#                 alt="recipe-image">#}
            {#            <div class="recipe-info">#}
            {#                Stir salt, paprika, cardamom, coriander, and black pepper together in a bowl. Add oil and maple syrup#}
            {#                and stir until evenly combined. Preheat a non-stick frying pan over medium-high heat, about 350 degrees#}
            {#                F (175 degrees C). Dredge salmon pieces through#}
            {#                the maple syrup mixture until evenly coated on all sides. Cook salmon in the preheated pan until fish#}
            {#                flakes easily with a fork, 5 to 7 minutes per side.#}
            {#            </div>#}
            {#            <div class="buttons-container">#}
            {#                <a class="button detail" href="./details.html">Details</a>#}
            {#                <a class="button edit" href="./edit.html">Edit</a>#}
            {#                <a class="button delete" href="./delete.html">Delete</a>#}
            {#            </div>#}
            {#        </div>#}

            {% for recipe in recipes %}

                <div class="item">
                    <h2>{{ recipe.title }}</h2>
                    <img class="detail-img"
                         src="{{ recipe.image_url }}"
                         alt="recipe-image">
                    <div class="recipe-info">
                        {{ recipe.description }}
                    </div>
                    <div class="buttons-container">
                        <a class="button detail" href="{% url 'details recipe' recipe_id=recipe.id %}">Details</a>
                        <a class="button edit" href="{% url 'edit recipe' recipe_id=recipe.id %}">Edit</a>
                        <a class="button delete" href="{% url 'delete recipe' recipe_id=recipe.id %}">Delete</a>
                    </div>
                </div>

            {% endfor %}

        </div>
    {% endif %}

</div>


</body>

</html>